"""initial schema for university enrollment

Revision ID: 0001_initial
Revises:
"""
from alembic import op
import sqlalchemy as sa

BIGINT = sa.BigInteger().with_variant(sa.Integer(), "sqlite")

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("plan", sa.Column("id_plan", sa.SmallInteger(), primary_key=True), sa.Column("nombre", sa.String(100), nullable=False, unique=True), sa.Column("anio_resolucion", sa.SmallInteger()), sa.Column("vigente", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_table("area_curricular", sa.Column("id_area", sa.SmallInteger(), primary_key=True), sa.Column("nombre_area", sa.String(100), nullable=False, unique=True))
    op.create_table("ciclo", sa.Column("id_ciclo", BIGINT, primary_key=True), sa.Column("id_plan", sa.SmallInteger(), sa.ForeignKey("plan.id_plan", ondelete="RESTRICT"), nullable=False), sa.Column("numero_ciclo", sa.SmallInteger(), nullable=False), sa.Column("nombre_ciclo", sa.String(50), nullable=False), sa.Column("anio", sa.SmallInteger()), sa.Column("total_creditos_declarado", sa.Numeric(5, 2)), sa.Column("total_asignaturas_declarado", sa.SmallInteger()), sa.UniqueConstraint("id_plan", "numero_ciclo"), sa.UniqueConstraint("id_ciclo", "id_plan"), sa.CheckConstraint("numero_ciclo BETWEEN 1 AND 10"))
    op.create_table("curso", sa.Column("id_curso", BIGINT, primary_key=True), sa.Column("id_plan", sa.SmallInteger(), sa.ForeignKey("plan.id_plan", ondelete="RESTRICT"), nullable=False), sa.Column("codigo_curso", sa.String(20), nullable=False), sa.Column("nombre_curso", sa.String(200), nullable=False), sa.Column("id_ciclo", BIGINT, nullable=False), sa.Column("creditos", sa.Numeric(4, 2), nullable=False), sa.Column("id_area", sa.SmallInteger(), sa.ForeignKey("area_curricular.id_area", ondelete="SET NULL")), sa.Column("codigo_certificacion", sa.String(50)), sa.Column("mencion_electiva", sa.String(150)), sa.ForeignKeyConstraint(["id_ciclo", "id_plan"], ["ciclo.id_ciclo", "ciclo.id_plan"], ondelete="RESTRICT"), sa.UniqueConstraint("id_plan", "codigo_curso"), sa.UniqueConstraint("id_curso", "id_plan"), sa.CheckConstraint("creditos > 0"))
    op.create_table("prerrequisito", sa.Column("id_plan", sa.SmallInteger(), sa.ForeignKey("plan.id_plan", ondelete="CASCADE"), primary_key=True), sa.Column("id_curso", BIGINT, primary_key=True), sa.Column("id_prerrequisito", BIGINT, primary_key=True), sa.ForeignKeyConstraint(["id_curso", "id_plan"], ["curso.id_curso", "curso.id_plan"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["id_prerrequisito", "id_plan"], ["curso.id_curso", "curso.id_plan"], ondelete="RESTRICT"), sa.CheckConstraint("id_curso <> id_prerrequisito"))
    op.create_table("alumno", sa.Column("cod_alumno", sa.String(20), primary_key=True), sa.Column("nombres", sa.String(120), nullable=False), sa.Column("apellidos", sa.String(120), nullable=False), sa.Column("email", sa.String(254), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("id_plan", sa.SmallInteger(), sa.ForeignKey("plan.id_plan", ondelete="RESTRICT"), nullable=False), sa.Column("estado", sa.String(12), nullable=False), sa.Column("fecha_ingreso", sa.Date(), nullable=False), sa.CheckConstraint("estado IN ('activo','egresado','retirado')"))
    op.create_table("periodo_academico", sa.Column("id_periodo", BIGINT, primary_key=True), sa.Column("cod_per_acad", sa.String(20), nullable=False, unique=True), sa.Column("fecha_inicio", sa.Date(), nullable=False), sa.Column("fecha_fin", sa.Date(), nullable=False), sa.Column("estado", sa.String(12), nullable=False), sa.CheckConstraint("fecha_fin > fecha_inicio"), sa.CheckConstraint("estado IN ('planificado','en_curso','cerrado')"))
    op.create_table("docente", sa.Column("cod_docente", sa.String(20), primary_key=True), sa.Column("nombres", sa.String(120), nullable=False), sa.Column("apellidos", sa.String(120), nullable=False), sa.Column("email", sa.String(254), nullable=False, unique=True))
    op.create_table("aula", sa.Column("cod_aula", sa.String(20), primary_key=True), sa.Column("pabellon", sa.String(60), nullable=False), sa.Column("capacidad", sa.SmallInteger(), nullable=False), sa.Column("tipo", sa.String(15), nullable=False), sa.CheckConstraint("capacidad > 0"), sa.CheckConstraint("tipo IN ('teoria','laboratorio')"))
    op.create_table("seccion", sa.Column("id_seccion", BIGINT, primary_key=True), sa.Column("id_curso", BIGINT, sa.ForeignKey("curso.id_curso", ondelete="RESTRICT"), nullable=False), sa.Column("id_periodo", BIGINT, sa.ForeignKey("periodo_academico.id_periodo", ondelete="RESTRICT"), nullable=False), sa.Column("cod_docente", sa.String(20), sa.ForeignKey("docente.cod_docente", ondelete="RESTRICT"), nullable=False), sa.Column("cod_aula", sa.String(20), sa.ForeignKey("aula.cod_aula", ondelete="RESTRICT"), nullable=False), sa.Column("nro_seccion", sa.String(10), nullable=False), sa.Column("cupo_maximo", sa.SmallInteger(), nullable=False), sa.Column("cupo_disponible", sa.SmallInteger(), nullable=False), sa.Column("dia", sa.SmallInteger(), nullable=False), sa.Column("hora_inicio", sa.Time(), nullable=False), sa.Column("hora_fin", sa.Time(), nullable=False), sa.UniqueConstraint("id_curso", "id_periodo", "nro_seccion"), sa.CheckConstraint("cupo_maximo > 0"), sa.CheckConstraint("cupo_disponible BETWEEN 0 AND cupo_maximo"), sa.CheckConstraint("dia BETWEEN 1 AND 7"), sa.CheckConstraint("hora_fin > hora_inicio"))
    op.create_table("matricula", sa.Column("nro_matricula", BIGINT, primary_key=True), sa.Column("cod_alumno", sa.String(20), sa.ForeignKey("alumno.cod_alumno", ondelete="RESTRICT"), nullable=False), sa.Column("id_periodo", BIGINT, sa.ForeignKey("periodo_academico.id_periodo", ondelete="RESTRICT"), nullable=False), sa.Column("fecha_matricula", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("estado", sa.String(12), nullable=False), sa.Column("monto_pagado", sa.Numeric(10, 2), nullable=False, server_default="0"), sa.UniqueConstraint("cod_alumno", "id_periodo"), sa.CheckConstraint("estado IN ('pendiente','confirmada','anulada')"), sa.CheckConstraint("monto_pagado >= 0"))
    op.create_table("matricula_detalle", sa.Column("id", BIGINT, primary_key=True), sa.Column("nro_matricula", BIGINT, sa.ForeignKey("matricula.nro_matricula", ondelete="CASCADE"), nullable=False), sa.Column("id_seccion", BIGINT, sa.ForeignKey("seccion.id_seccion", ondelete="RESTRICT"), nullable=False), sa.Column("estado", sa.String(12), nullable=False), sa.Column("nota_final", sa.Numeric(4, 2)), sa.UniqueConstraint("nro_matricula", "id_seccion"), sa.CheckConstraint("estado IN ('matriculado','retirado')"), sa.CheckConstraint("nota_final BETWEEN 0 AND 20"))


def downgrade():
    for table in ("matricula_detalle", "matricula", "seccion", "aula", "docente", "periodo_academico", "alumno", "prerrequisito", "curso", "ciclo", "area_curricular", "plan"):
        op.drop_table(table)
